### ISSUE TITLE
Profile edit

### ISSUE THREAD

**Issue by kazhamiakin** [smartcommunitylab/gi-pro#12]
- Create a field in Professional to store user-defined field values (e.g., phone);
- API method to update these fields.
- merge CNF data into the Professional object when calling getProfile API method.

**Comment by micnori** [comment]
Mi serve la lista dei dati da mappare da CNF

**Comment by micnori** [comment]
Professional already have a `Map<String, Object> customProperties` filed

**Comment by micnori** [comment]
add API to update professional phone
