### ISSUE TITLE
Icona posizione vs icona professionisti

### ISSUE THREAD

**Issue by westwind28** [smartcommunitylab/gi-pro#34]
Aprendo la mappa con geolocalizzazione attiva, la propria posizione viene mostrata con la puntina azzurra, uguale a quella che mostra dove si trovano i vari professionisti --> non è immediato capire che una è la mia posizione attuale e gli altri i diversi professionisti.
Potrebbe essere utile cambiare colore o tipo di icona per identificare la posizione dei professionisti

**Comment by oskarnrk** [comment]
Concordo pienamente con questa cosa. Chiediamo a Raman e poi a Paola per cambiare marker.
