### ISSUE TITLE
iOS: Lista professionisti limitata

### ISSUE THREAD

**Issue by westwind28** [smartcommunitylab/gi-pro#64]
La lista dei professionisti è limitata a 5 persone, provando a registrarsi non ci si trova in elenco.
Nell'elenco dei servizi compaiono invece i servizi di tutti gli utenti

**Comment by oskarnrk** [comment]
@kazhamiakin escono solo quelli geolocalizzati, non si possono avere a cascata in ordine alfabetico quelli non geolocalizzati?

**Comment by oskarnrk** [comment]
Questa issue non dovrebbe presentarsi in quanto tutti i professionisti devono dare una posizione. Il problema sta in eventuali bachi sulla registrazione. Chiudo.
